# Generated by Django 3.0.5 on 2020-04-25 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scopes', '0001_initial'),
        ('vi_lomas_changes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverageMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('change_area', models.FloatField()),
                ('perc_change_area', models.FloatField()),
                ('scope', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vi_lomas_changes_scope', to='scopes.Scope')),
            ],
            options={
                'unique_together': {('date_from', 'date_to', 'scope')},
            },
        ),
    ]
