# Generated by Django 3.0.5 on 2020-04-27 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vi_lomas_changes', '0004_add_created_updated_fields_to_coverage_measurements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
            ],
        ),
    ]
