# Generated by Django 3.0.5 on 2020-04-28 02:50

from django.db import migrations, models
import vi_lomas_changes.models


class Migration(migrations.Migration):

    dependencies = [
        ('vi_lomas_changes', '0008_coveragemeasurement_changes_mask'),
    ]

    operations = [
        migrations.AddField(
            model_name='raster',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=vi_lomas_changes.models.raster_path),
        ),
    ]
