# Generated by Django 3.0.5 on 2020-04-28 02:52

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vi_lomas_changes', '0009_raster_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raster',
            name='area_geom',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
