# Generated by Django 3.0.5 on 2020-04-28 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vi_lomas_changes', '0010_auto_20200428_0252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raster',
            old_name='area_geom',
            new_name='extent_geom',
        ),
    ]
