# Generated by Django 3.0.5 on 2020-04-29 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vi_lomas_changes', '0012_auto_20200428_2032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VegetationMask',
        ),
    ]
