# Generated by Django 3.0.6 on 2020-05-06 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vi_lomas_changes', '0013_delete_vegetationmask'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='period',
            unique_together={('date_from', 'date_to')},
        ),
    ]
