# Generated by Django 3.0.6 on 2020-05-15 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vi_lomas_changes', '0014_auto_20200506_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raster',
            name='extent_geom',
        ),
    ]
