# Generated by Django 3.0.10 on 2020-12-16 13:13

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import eo_sensors.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scopes', '0002_auto_20200428_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('date', models.DateField(null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=eo_sensors.models.raster_path)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('extra_fields', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('slug', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CoverageRaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cov_rast', django.contrib.gis.db.models.fields.RasterField(srid=32718)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eo_sensors.Raster')),
            ],
        ),
        migrations.CreateModel(
            name='CoverageMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('kind', models.CharField(max_length=2)),
                ('area', models.FloatField()),
                ('perc_area', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eo_sensors_coveragemeasurement_related', to='scopes.Scope')),
            ],
            options={
                'unique_together': {('date', 'scope', 'kind')},
            },
        ),
    ]
