# Generated by Django 3.0.10 on 2020-12-22 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scopes', '0002_auto_20200428_2233'),
        ('eo_sensors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coveragemeasurement',
            name='source',
            field=models.CharField(blank=True, choices=[('S2', 'Sentinel-2'), ('P1', 'PeruSat-1'), ('MV', 'MODIS VI')], max_length=2),
        ),
        migrations.AddField(
            model_name='raster',
            name='source',
            field=models.CharField(blank=True, choices=[('S2', 'Sentinel-2'), ('P1', 'PeruSat-1'), ('MV', 'MODIS VI')], max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='coveragemeasurement',
            unique_together={('date', 'scope', 'source', 'kind')},
        ),
    ]
