# Generated by Django 3.1.6 on 2021-03-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eo_sensors', '0002_auto_20201222_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raster',
            name='extra_fields',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
