# Generated by Django 3.1.6 on 2021-03-23 15:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eo_sensors', '0003_auto_20210322_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverageMask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('source', models.CharField(blank=True, choices=[('S2', 'Sentinel-2'), ('P1', 'PeruSat-1'), ('MV', 'MODIS VI')], max_length=2)),
                ('kind', models.CharField(blank=True, max_length=2, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eo_sensors.raster')),
            ],
            options={
                'unique_together': {('date', 'source', 'kind')},
            },
        ),
    ]
