# Generated by Django 3.1.6 on 2021-04-25 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eo_sensors', '0004_coveragemask'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='raster',
            unique_together={('date', 'source', 'slug')},
        ),
    ]
