# Generated by Django 3.1.8 on 2021-08-28 00:23

from datetime import timedelta

from django.db import migrations
from eo_sensors.models import Sources


def fix_raster_dates(apps, schema_editor):
    Raster = apps.get_model("eo_sensors", "Raster")
    for raster in Raster.objects.filter(source=Sources.MODIS_VI):
        raster.date = raster.date - timedelta(days=1)
        raster.save()


class Migration(migrations.Migration):

    dependencies = [
        ("eo_sensors", "0005_auto_20210425_1946"),
    ]

    operations = [
        migrations.RunPython(fix_raster_dates, migrations.RunPython.noop),
    ]
