# Generated by Django 3.1.8 on 2021-08-28 01:34

from datetime import timedelta

from django.db import migrations
from eo_sensors.models import Sources


def fix_coverage_dates(apps, schema_editor):
    CoverageMask = apps.get_model("eo_sensors", "CoverageMask")
    CoverageMeasurement = apps.get_model("eo_sensors", "CoverageMeasurement")
    for mask in CoverageMask.objects.filter(source=Sources.MODIS_VI):
        mask.date = mask.date - timedelta(days=1)
        mask.save()
    for measurement in CoverageMeasurement.objects.filter(source=Sources.MODIS_VI):
        measurement.date = measurement.date - timedelta(days=1)
        measurement.save()


class Migration(migrations.Migration):

    dependencies = [
        ("eo_sensors", "0006_fix_raster_dates"),
    ]

    operations = [
        migrations.RunPython(fix_coverage_dates, migrations.RunPython.noop),
    ]
