# Generated by Django 2.2.7 on 2019-11-07 02:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('location', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('datetime', models.DateTimeField(blank=True, default=datetime.datetime.now, primary_key=True, serialize=False)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='measures.Device')),
            ],
            options={
                'unique_together': {('datetime', 'device')},
            },
        ),
        migrations.RunSQL(
            "SELECT create_hypertable('measures_measure', 'datetime');",
        )
    ]
