# Generated by Django 3.0.2 on 2020-01-25 13:37

import django.contrib.postgres.fields.jsonb
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0002_create_measure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measure',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True,
                                       default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True,
                                                                 null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
