# Generated by Django 3.0.2 on 2020-02-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0004_fix_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='code',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
