# Generated by Django 3.0.10 on 2020-09-24 18:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='args',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, verbose_name='arguments'),
        ),
        migrations.AlterField(
            model_name='job',
            name='internal_metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='internal metadata'),
        ),
        migrations.AlterField(
            model_name='job',
            name='kwargs',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='keyword arguments'),
        ),
        migrations.AlterField(
            model_name='job',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='metadata'),
        ),
    ]
