# Generated by Django 3.1.6 on 2021-03-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='args',
            field=models.JSONField(blank=True, default=list, verbose_name='arguments'),
        ),
        migrations.AlterField(
            model_name='job',
            name='internal_metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='internal metadata'),
        ),
        migrations.AlterField(
            model_name='job',
            name='kwargs',
            field=models.JSONField(blank=True, default=dict, verbose_name='keyword arguments'),
        ),
        migrations.AlterField(
            model_name='job',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='metadata'),
        ),
        migrations.AlterField(
            model_name='joblogentry',
            name='log',
            field=models.JSONField(),
        ),
    ]
