# Generated by Django 2.2.9 on 2020-03-18 17:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('CE', 'Corredores Ecologicos'), ('AC', 'ACR'), ('DI', 'Distritos'), ('EF', 'Ecosistemas fragiles'), ('SA', 'Sitios arqueologicos')], max_length=2)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
    ]
