# Generated by Django 2.2.9 on 2020-03-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scopes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scope',
            name='type_scope',
            field=models.CharField(choices=[('CO', 'Corredores')], default='CO', max_length=2),
            preserve_default=False,
        ),
    ]
