# Generated by Django 3.0.5 on 2020-04-28 22:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scopes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scope',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scope',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
