# Generated by Django 3.1.6 on 2021-05-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scopes', '0002_auto_20200428_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='scope_type',
            field=models.CharField(choices=[('CE', 'Corredores Ecologicos'), ('AC', 'ACR'), ('DI', 'Distritos'), ('EF', 'Ecosistemas fragiles'), ('SA', 'Sitios arqueologicos'), ('UD', 'Definido por usuario')], max_length=2),
        ),
    ]
