# Generated by Django 2.2.9 on 2020-01-10 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='period',
        ),
        migrations.DeleteModel(
            name='Period',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
