# Generated by Django 3.0.5 on 2020-04-15 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0006_rename_fks'),
    ]

    operations = [
        migrations.DeleteModel(name='Measure', ),
    ]
