# Generated by Django 3.0.5 on 2020-04-23 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0007_delete_measure'),
        ('stations', '0007_prediction'),
    ]

    operations = [
    ]
