# Generated by Django 3.1.6 on 2021-03-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0009_change_meta_on_predictions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
