# Generated by Django 3.1.8 on 2021-08-28 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0010_auto_20210322_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='station',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='station',
            name='place',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
