# Generated by Django 3.1.8 on 2021-08-28 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0011_auto_20210828_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='code',
            field=models.CharField(max_length=30),
        ),
    ]
