# Generated by Django 3.1.8 on 2021-08-28 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0013_auto_20210828_0233"),
    ]

    operations = [
        migrations.RunSQL(
            ["ALTER TABLE stations_measurement ADD site_id int NULL"],
            ["ALTER TABLE stations_measurement DROP site_id"],
        )
    ]
