# Generated by Django 3.1.8 on 2021-08-28 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0014_add_site_to_measurements'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stations.station'),
        ),
    ]
