# Generated by Django 3.1.8 on 2021-08-28 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0015_site_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='attributes',
        ),
    ]
