# Generated by Django 3.1.8 on 2021-08-28 13:32

from django.contrib.postgres.operations import HStoreExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0016_remove_site_attributes"),
    ]

    operations = [
        HStoreExtension(),
    ]
