# Generated by Django 3.0.5 on 2020-04-14 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lomas_changes', '0003_add_finished_period_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='period',
            old_name='end_date',
            new_name='date_from',
        ),
        migrations.RenameField(
            model_name='period',
            old_name='init_date',
            new_name='date_to',
        ),
        migrations.RemoveField(
            model_name='period',
            name='s1_finished',
        ),
        migrations.RemoveField(
            model_name='period',
            name='s2_finished',
        ),
    ]
