# Generated by Django 3.0.5 on 2020-04-14 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lomas_changes', '0004_rename_period_fields'),
    ]

    operations = [
        migrations.DeleteModel(name='Product', ),
    ]
