# Generated by Django 3.0.5 on 2020-04-14 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scopes', '0001_initial'),
        ('lomas_changes', '0005_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverageMeasurement',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('change_area', models.FloatField()),
                ('perc_change_area', models.FloatField()),
                ('period',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                   to='lomas_changes.Period')),
                ('scope',
                 models.ForeignKey(
                     null=True,
                     on_delete=django.db.models.deletion.SET_NULL,
                     to='scopes.Scope')),
            ],
        ),
    ]
