# Generated by Django 3.0.5 on 2020-04-25 19:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scopes', '0001_initial'),
        ('lomas_changes', '0006_coveragemeasurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='coveragemeasurement',
            name='date_from',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coveragemeasurement',
            name='date_to',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coveragemeasurement',
            name='scope',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lomas_changes_scope', to='scopes.Scope'),
        ),
        migrations.AlterUniqueTogether(
            name='coveragemeasurement',
            unique_together={('date_from', 'date_to', 'scope')},
        ),
        migrations.RemoveField(
            model_name='coveragemeasurement',
            name='period',
        ),
    ]
