# Generated by Django 3.0.5 on 2020-04-25 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scopes', '0001_initial'),
        ('lomas_changes', '0007_auto_20200425_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coveragemeasurement',
            name='scope',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lomas_changes_coveragemeasurement_related', to='scopes.Scope'),
        ),
    ]
