# Generated by Django 3.0.5 on 2020-04-28 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lomas_changes', '0011_changesmask_mask'),
    ]

    operations = [
        migrations.AddField(
            model_name='coveragemeasurement',
            name='changes_mask',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lomas_changes.ChangesMask'),
        ),
    ]
