# Generated by Django 3.0.5 on 2020-05-03 19:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import lomas_changes.models


class Migration(migrations.Migration):

    dependencies = [
        ('lomas_changes', '0012_coveragemeasurement_changes_mask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raster',
            name='area_geom',
        ),
        migrations.AddField(
            model_name='raster',
            name='extent_geom',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='raster',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=lomas_changes.models.raster_path),
        ),
    ]
