# Generated by Django 3.0.6 on 2020-05-06 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lomas_changes', '0013_auto_20200503_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coveragemeasurement',
            old_name='change_area',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='coveragemeasurement',
            old_name='perc_change_area',
            new_name='perc_area',
        ),
        migrations.RemoveField(
            model_name='coveragemeasurement',
            name='changes_mask',
        ),
        migrations.DeleteModel(
            name='ChangesMask',
        ),
    ]
