# Generated by Django 3.0.6 on 2020-05-07 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lomas_changes', '0016_object'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='object',
            unique_together=set(),
        ),
    ]
