# Generated by Django 3.0.10 on 2020-11-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lomas_changes', '0018_remove_raster_extent_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='raster',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='raster',
            unique_together={('slug', 'date')},
        ),
        migrations.RemoveField(
            model_name='raster',
            name='period',
        ),
    ]
