# Generated by Django 3.0.10 on 2020-11-08 16:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lomas_changes', '0021_replace_date_from_to_for_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverageRaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cov_rast', django.contrib.gis.db.models.fields.RasterField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lomas_changes.Raster')),
            ],
        ),
    ]
