# Generated by Django 3.0.10 on 2020-12-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scopes', '0002_auto_20200428_2233'),
        ('lomas_changes', '0023_auto_20201204_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='coveragemeasurement',
            name='kind',
            field=models.CharField(default='LS', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='coveragemeasurement',
            unique_together={('date', 'scope', 'kind')},
        ),
    ]
