# Generated by Django 3.0.5 on 2020-04-25 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('alerts', '0006_auto_20200425_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.PositiveIntegerField()),
                ('measurement_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('measurement_content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'lomas_changes'), ('model', 'coveragemeasurement')), models.Q(('app_label', 'vi_lomas_changes'), ('model', 'coveragemeasurement')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('rule_content_type', models.ForeignKey(limit_choices_to=models.Q(('model', 'scopetyperule'), ('model', 'scoperule'), ('model', 'parameterrule'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='alert_related', to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
