# Generated by Django 3.0.5 on 2020-04-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0008_alertcheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterrule',
            name='is_absolute',
            field=models.BooleanField(default=False),
        ),
    ]
