# Generated by Django 3.0.5 on 2020-04-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0010_auto_20200426_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterrule',
            name='valid_min',
            field=models.FloatField(default=-5),
        ),
        migrations.AlterField(
            model_name='scoperule',
            name='valid_min',
            field=models.FloatField(default=-5),
        ),
        migrations.AlterField(
            model_name='scopetyperule',
            name='valid_min',
            field=models.FloatField(default=-5),
        ),
    ]
