# Generated by Django 3.0.5 on 2020-04-26 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('alerts', '0011_auto_20200426_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='measurement_content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'lomas_changes'), ('model', 'coveragemeasurement')), models.Q(('app_label', 'vi_lomas_changes'), ('model', 'coveragemeasurement')), models.Q(('app_label', 'stations'), ('model', 'measurement')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
