# Generated by Django 3.0.5 on 2020-04-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0012_fix_measurement_content_type_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
