# Generated by Django 3.0.5 on 2020-05-01 22:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0013_alert_last_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='rule_attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
