# Generated by Django 3.0.6 on 2020-05-14 23:31

from django.db import migrations
from django.conf import settings


def create_user_profiles(apps, schema_editor):
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    UserProfile = apps.get_model('alerts', 'UserProfile')

    for user in User.objects.all():
        UserProfile.objects.get_or_create(user=user)


class Migration(migrations.Migration):
    dependencies = [
        ('alerts', '0015_userprofile'),
    ]

    operations = [
        migrations.RunPython(create_user_profiles),
    ]
