# Generated by Django 3.0.6 on 2020-05-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0017_auto_20200525_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='value',
            field=models.FloatField(null=True),
        ),
    ]
