# Generated by Django 3.0.10 on 2020-12-18 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('alerts', '0018_alert_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='measurement_content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'eo_sensors'), ('model', 'coveragemeasurement')), models.Q(('app_label', 'stations'), ('model', 'measurement')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='scoperule',
            name='measurement_content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(('app_label', 'eo_sensors'), ('model', 'coveragemeasurement')), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='scopetyperule',
            name='measurement_content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(('app_label', 'eo_sensors'), ('model', 'coveragemeasurement')), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
