# Generated by Django 3.1.6 on 2021-03-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0019_auto_20201218_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='rule_attributes',
            field=models.JSONField(default=dict),
        ),
    ]
