# Generated by Django 3.1.6 on 2021-05-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0020_auto_20210322_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scopetyperule',
            name='scope_type',
            field=models.CharField(choices=[('CE', 'Corredores Ecologicos'), ('AC', 'ACR'), ('DI', 'Distritos'), ('EF', 'Ecosistemas fragiles'), ('SA', 'Sitios arqueologicos'), ('UD', 'Definido por usuario')], max_length=2),
        ),
    ]
