# Generated by Django 2.2.9 on 2020-01-10 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('init_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('datetime', models.DateTimeField(null=True)),
                ('concatenated', models.BooleanField(default=False)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='files.Period')),
            ],
        ),
    ]
