# Generated by Django 2.2.9 on 2020-01-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='s1_finished',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='period',
            name='s2_finished',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sensor_type',
            field=models.CharField(choices=[('S1', 'Sentinel1'), ('S2', 'Sentinel2')], default='S1', max_length=2),
            preserve_default=False,
        ),
    ]
