# Generated by Django 2.2.9 on 2020-01-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20200115_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='s1_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='period',
            name='s2_finished',
            field=models.BooleanField(default=False),
        ),
    ]
